version: "3"

services:
  nginx:
    image: nginx:stable
    ports:
      - "3000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

  api:
    build: ./api
    command: "bash ./scripts/entrypoint.sh"
    env_file:
      - ./api/configs/dev_environment
      - ./geoserver/configs/postgis
    volumes:
      - ./api:/home/python/workspace
      - ./api/data:/home/python/.local
    depends_on:
      - geoserver
      - nginx

  geoserver:
    image: kartoza/geoserver:2.22.0
    depends_on:
      - postgis
    volumes:
      - ./geoserver/data/geoserver:/opt/geoserver/data_dir
    env_file:
      - ./geoserver/configs/geoserver

  postgis:
    image: postgis/postgis:14-3.3
    volumes:
      - ./api/initializers/db:/docker-entrypoint-initdb.d:delegated
      - ./geoserver/data/pg_data:/var/lib/postgresql/data
    env_file:
      - ./geoserver/configs/postgis

  helper:
    image: debian:11-slim
    volumes:
      - ./api/data:/workspace/api/local
      - ./api/__pycache__:/workspace/api/pycache
      - ./geoserver/data/geoserver:/workspace/geoserver
