{{- if .Values.tls.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "ump.fullname" . }}
  labels:
    app.kubernetes.io/name: urban-model-platform-api
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: urban-model-platform
    {{- include "ump.labels" . | nindent 4 }}
spec:
  secretName: {{ printf "%s-tls" (include "ump.fullname" .) }}
  dnsNames:
    - {{ .Values.tls.gateway.hostName }}
  issuerRef:
    name: {{ include "ump.issuer" . }}
    kind: Issuer
    group: cert-manager.io
{{ end }}