apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-prod
  labels:
    app.kubernetes.io/name: urban-model-platform-api
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: urban-model-platform
    {{- include "ump.labels" . | nindent 4 }}
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: analytics@gv.hamburg.de
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
      - http01:
          gatewayHTTPRoute:
            parentRefs:
              - name: ump-gateway
                namespace: ump-api
                kind: "Gateway"
                group: "gateway.networking.k8s.io"
