apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "ump.fullname" . }}-db-migrate
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  backoffLimit: 3
  template:
    spec:
      containers:
      - name: db-migrate
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        command: ["flask", "db", "upgrade"]
        env:
          {{- include "ump.databaseEnv" . | nindent 10 }}
      restartPolicy: Never