apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "ump.fullname" . }}-db-migrate
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  backoffLimit: 3
  template:
    spec:
      {{- with .Values.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: db-migrate
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        command: ["flask", "db", "upgrade"]
        volumeMounts:
          - name: tmp-volume
            mountPath: /tmp
          - name: providers-volume
            mountPath: {{ .Values.config.providersFilePath | quote }}
            subPath: providers.yaml
            readOnly: true
        env:
          - name: POSTGRES_DB
            valueFrom:
              secretKeyRef:
                name: {{ .Values.postgresConnection.existingSecret.name }}
                key: dbname
          {{- if not .Values.config.postgresHost }}
          - name: POSTGRES_HOST
            valueFrom:
              secretKeyRef:
                name: {{ .Values.postgresConnection.existingSecret.name }}
                key: host
          {{- end }}
          {{- if not .Values.config.postgresPort }}
          - name: POSTGRES_PORT
            valueFrom:
              secretKeyRef:
                name: {{ .Values.postgresConnection.existingSecret.name }}
                key: port
          {{- end }}
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: {{ .Values.postgresConnection.existingSecret.name }}
                key: user
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Values.postgresConnection.existingSecret.name }}
                key: password
          - name: FLASK_APP
            value: "ump.main"
      restartPolicy: Never
      volumes:
        - name: tmp-volume
          emptyDir: {}
        - name: providers-volume
          configMap:
          {{- if not .Values.providers.existingConfigMap.name }}
            name: {{ include "ump.fullname" . }}-providers
          {{- else }}
            name: {{ .Values.providers.existingConfigMap.name }}
          {{- end }}
