apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "ump.fullname" . }}-job-reader
  labels:
    {{- include "ump.labels" . | nindent 4 }}
rules:
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["get", "watch", "list"]
