# rolebinding-job.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "ump.fullname" . }}-job-reader
  labels:
    {{- include "ump.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "ump.fullname" . }}-job-reader
subjects:
- kind: ServiceAccount
  name: {{ include "ump.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}